#!/bin/bash
#
# Pull OAuth client credentials and the PostHog analytics key from the Doppler
# `sync-bar` project into Secrets.xcconfig (gitignored), which the build bakes
# into Info.plist.
#
# Usage:
#   ./scripts/pull-secrets.sh [config]      # config defaults to "dev"
#
# Requires: doppler CLI logged in with access to the sync-bar project.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

PROJECT="${DOPPLER_PROJECT:-sync-bar}"
CONFIG="${1:-${DOPPLER_CONFIG:-dev}}"
OUT="$REPO_ROOT/Secrets.xcconfig"

if ! command -v doppler >/dev/null 2>&1; then
  echo "Error: doppler CLI not found. brew install dopplerhq/cli/doppler"
  exit 1
fi

KEYS=(
  NOTION_CLIENT_ID NOTION_CLIENT_SECRET
  LINEAR_CLIENT_ID LINEAR_CLIENT_SECRET
  GOOGLE_CLIENT_ID GOOGLE_CLIENT_SECRET
  X_CLIENT_ID X_CLIENT_SECRET
  POSTHOG_API_KEY
  POLAR_ORG_ID POLAR_CHECKOUT_URL POLAR_PORTAL_URL POLAR_USAGE_RELAY_URL
  POLAR_RELAY_TOKEN
)

echo "==> Pulling OAuth credentials from Doppler ($PROJECT/$CONFIG)"
{
  echo "// Generated by scripts/pull-secrets.sh from Doppler $PROJECT/$CONFIG. Do not commit."
  for key in "${KEYS[@]}"; do
    value="$(doppler secrets get "$key" --project "$PROJECT" --config "$CONFIG" --plain 2>/dev/null || true)"
    echo "$key = $value"
  done
} > "$OUT"

echo "==> Wrote $OUT"
